services:
  order-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8081
      - SKIP_DB_MIGRATION=true
      - Redis__EnableCaching=true
      - UserService__BaseUrl=http://user-api:8080
      
    
  user-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - SKIP_DB_MIGRATION=true
      
      
  notification-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8082
      
