services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  order-api:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Change from 8080:8080 to 8081:8081
    environment:
      - MessageBroker__Provider=RabbitMQ
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq

  user-api:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Change from 8081:8081 to 8080:8080

  notification-api:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - MessageBroker__Provider=RabbitMQ
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
