services:
  order-api:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  user-api:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  notification-api:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
