services:
  # UserService
  - type: web
    name: swiggy-userservice
    runtime: docker
    plan: free
    dockerfilePath: ./UserService/Dockerfile
    dockerContext: ./UserService
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
      - key: DATABASE_URL
        fromDatabase:
          name: swiggy-shared-db
          property: connectionString

  # OrderService
  - type: web
    name: swiggy-orderservice
    runtime: docker
    plan: free
    dockerfilePath: ./OrderService/Dockerfile
    dockerContext: ./OrderService
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
      - key: DATABASE_URL
        fromDatabase:
          name: swiggy-shared-db
          property: connectionString

  # NotificationService
  - type: web
    name: swiggy-notificationservice
    runtime: docker
    plan: free
    dockerfilePath: ./NotificationService/Dockerfile
    dockerContext: ./NotificationService
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT

databases:
  - name: swiggy-shared-db
    databaseName: swiggy_main
    plan: free