services:
  # UserService
  - type: web
    name: userservice
    runtime: docker
    plan: free
    dockerfilePath: ./UserService/Dockerfile
    dockerContext: ./UserService
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
      - key: DATABASE_URL
        fromDatabase:
          name: userservice-db
          property: connectionString

  # OrderService  
  - type: web
    name: orderservice
    runtime: docker
    plan: free
    dockerfilePath: ./OrderService/Dockerfile
    dockerContext: ./OrderService
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT
      - key: DATABASE_URL
        fromDatabase:
          name: orderservice-db
          property: connectionString

  # NotificationService
  - type: web
    name: notificationservice
    runtime: docker
    plan: free
    dockerfilePath: ./NotificationService/Dockerfile
    dockerContext: ./NotificationService
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT

databases:
  - name: userservice-db
    databaseName: userdb
    plan: free

  - name: orderservice-db
    databaseName: orderdb
    plan: free